# Generated by Django 4.2 on 2023-10-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prospectuses",
            "0002_course_carrers_course_duration_course_eligibility_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="nqf_level_name",
            field=models.CharField(max_length=15),
        ),
    ]
