# Generated by Django 4.2 on 2023-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospectuses", "0003_alter_course_nqf_level_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="undergraduatedetail",
            name="application_fee_amount",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="undergraduatedetail",
            name="application_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="university",
            name="city",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="university",
            name="description",
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name="university",
            name="logo",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="university",
            name="province",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="university",
            name="website",
            field=models.URLField(max_length=255),
        ),
    ]
