# Generated by Django 4.2 on 2023-10-08 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prospectuses", "0005_rename_carrers_course_careers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UndergraduateDetail",
            new_name="ApplicationDetail",
        ),
    ]
