# Generated by Django 4.2 on 2023-10-08 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prospectuses", "0006_rename_undergraduatedetail_applicationdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationdetail",
            old_name="application_close",
            new_name="application_close_date",
        ),
        migrations.RenameField(
            model_name="applicationdetail",
            old_name="application_open",
            new_name="application_open_date",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="duration",
            new_name="duration_in_years",
        ),
        migrations.RenameField(
            model_name="university",
            old_name="logo",
            new_name="logo_url",
        ),
    ]
