# Generated by Django 4.2 on 2023-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospectuses", "0009_subject_admissionpointscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="university",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
