# Generated by Django 4.2 on 2023-10-15 17:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prospectuses", "0010_faculty_slug_university_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_fee_amount",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "application_method",
                    models.CharField(
                        choices=[
                            ("Online", "Apply Online"),
                            ("In-Person", "Apply In-Person"),
                        ],
                        default="Online",
                        max_length=20,
                    ),
                ),
                ("application_url", models.URLField()),
                ("application_open_date", models.DateField()),
                ("application_close_date", models.DateField()),
                ("additional_information", ckeditor.fields.RichTextField()),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prospectuses.university",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="applicationdetail",
            name="university",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdmissionPointScore",
        ),
        migrations.DeleteModel(
            name="ApplicationDetail",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
