# Generated by Django 4.2 on 2023-10-24 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prospectuses", "0011_applicationinformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="standardized_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="standardized_test_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="university",
            name="additional_information",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="university",
            name="application_close_date",
            field=models.DateField(default="2023-09-30"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="application_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="application_method",
            field=models.CharField(
                choices=[("Online", "Apply Online"), ("In-Person", "Apply In-Person")],
                default="Online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="application_open_date",
            field=models.DateField(default="2023-05-23"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="application_url",
            field=models.URLField(default="https://example.com/apply"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="contact_email",
            field=models.EmailField(default="admission@university.ac.za", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="contact_phone",
            field=models.CharField(default="+27 256 245 4578", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="university",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="university",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="university",
            name="twitter_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="description",
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name="ApplicationInformation",
        ),
    ]
