# Generated by Django 4.2 on 2023-10-02 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("favorites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bursary_applications",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applicants",
                        to="applications.bursaryapplication",
                    ),
                ),
                (
                    "favorite_bursaries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorited_by",
                        to="favorites.bursaryfavorite",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
