# Generated by Django 4.2 on 2023-10-22 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_delete_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
