# Generated by Django 4.2 on 2023-10-01 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bursaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BursaryApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TimeField(max_length=255)),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
                (
                    "bursary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bursaries.bursary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
