# Generated by Django 4.2 on 2023-10-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_alter_bursaryapplication_date_applied"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bursaryapplication",
            old_name="date_applied",
            new_name="application_date",
        ),
        migrations.AddField(
            model_name="bursaryapplication",
            name="application_status",
            field=models.CharField(default="Applied", max_length=60),
            preserve_default=False,
        ),
    ]
