# Generated by Django 4.2 on 2023-10-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0003_rename_date_applied_bursaryapplication_application_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursaryapplication",
            name="application_date",
            field=models.DateField(),
        ),
    ]
