# Generated by Django 4.2 on 2023-10-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_alter_bursaryapplication_application_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursaryapplication",
            name="application_date",
            field=models.DateField(null=True),
        ),
    ]
