# Generated by Django 4.2 on 2023-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0005_alter_bursaryapplication_application_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursaryapplication",
            name="notes",
            field=models.TextField(max_length=255),
        ),
    ]
