# Generated by Django 4.2 on 2023-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0007_courseapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursaryapplication",
            name="bursary",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="courseapplication",
            name="course",
            field=models.CharField(max_length=100),
        ),
    ]
