# Generated by Django 4.2 on 2023-10-22 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bursaries", "0008_alter_bursary_bursary_coverage"),
        ("favorites", "0002_rename_bursaryfavorite_favoritebursary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteBursary",
            new_name="BursaryFavorite",
        ),
    ]
