# Generated by Django 4.2 on 2023-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_organization",
            field=models.BooleanField(default=False),
        ),
    ]
