# Generated by Django 4.2 on 2023-09-29 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bursary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=60)),
                ("organization_description", ckeditor.fields.RichTextField()),
                ("bursary_description", ckeditor.fields.RichTextField()),
                ("eligibility_description", ckeditor.fields.RichTextField()),
                ("bursary_application_url", models.CharField(max_length=26)),
                ("bursary_covers", models.CharField(max_length=255)),
                ("fields_of_study", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=13)),
                ("is_full_coverage", models.BooleanField()),
                ("institution_supported", models.CharField(max_length=255)),
            ],
        ),
    ]
