# Generated by Django 4.2 on 2023-10-11 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bursaries", "0002_rename_email_bursary_contact_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bursary",
            old_name="bursary_covers",
            new_name="bursary_coverage",
        ),
    ]
