# Generated by Django 4.2 on 2023-10-11 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bursaries", "0003_rename_bursary_covers_bursary_bursary_coverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bursary",
            name="application_deadline",
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
