# Generated by Django 4.2 on 2023-10-11 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bursaries", "0004_bursary_application_deadline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bursary",
            old_name="fields_of_study",
            new_name="field_of_study",
        ),
    ]
