# Generated by Django 4.2 on 2023-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bursaries", "0005_rename_fields_of_study_bursary_field_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="bursary",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bursary",
            name="application_deadline",
            field=models.DateField(),
        ),
    ]
