# Generated by Django 4.2 on 2023-10-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bursaries", "0006_bursary_slug_alter_bursary_application_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursary",
            name="field_of_study",
            field=models.JSONField(),
        ),
    ]
