# Generated by Django 4.2 on 2023-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bursaries", "0007_alter_bursary_field_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bursary",
            name="bursary_coverage",
            field=models.JSONField(),
        ),
    ]
